if(EXISTS "D:/Coding/VisualStudios/Application/builds/ThePlant/Product/Dependencies/luacpp/Source/testLuaCompiler[1]_tests.cmake")
  include("D:/Coding/VisualStudios/Application/builds/ThePlant/Product/Dependencies/luacpp/Source/testLuaCompiler[1]_tests.cmake")
else()
  add_test(testLuaCompiler_NOT_BUILT testLuaCompiler_NOT_BUILT)
endif()
